services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=cablo
      - POSTGRES_USER=cablo
      - POSTGRES_PASSWORD=cablo
    volumes:
      - ./postgres/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - 5432:5432

  ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://db:5432/cablo
      DATASOURCES_DEFAULT_USERNAME: cablo
      DATASOURCES_DEFAULT_PASSWORD: cablo
    ports:
      - 8080:8080
    depends_on:
      - db
