services:
  postgres:
    image: cablo/postgres-image
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_DB=cablo
      - POSTGRES_USER=cablo
      - POSTGRES_PASSWORD=cablo
#    volumes:
#      - ./postgres/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - 5432:5432

  ms:
    image: cablo/ms-image
    build:
      context: .
      dockerfile: Dockerfile.ms
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://postgres:5432/cablo
      DATASOURCES_DEFAULT_USERNAME: cablo
      DATASOURCES_DEFAULT_PASSWORD: cablo
      env_cablo: Value from docker-compose.yaml
    ports:
      - 8000:8080
    depends_on:
      - postgres
