# used for debug against docker container only
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cablo
    driverClassName: org.postgresql.Driver
    username: cablo
    password: cablo
    dialect: POSTGRES
    db-type: postgres

micronaut:
  # serve static content from resources/public (copied from react build/ before kotlin build)
  router:
    static-resources:
      react:
        paths: classpath:public
        mapping: /public/**
  # allow to fetch data from react debug fe running on http://localhost:3000
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - "http://localhost:3000"

env_cablo: DEFAULT-VALUE-FOR-env-cablo